orders/urls.py
from django.views.generic import CreateView, UpdateView, DeleteView
from django.urls import path, reverse_lazy
from .models import Order, Category
from .views import OrderListView, CategoryListView


urlpatterns = [
    path('order/list/',
         OrderListView.as_view(),
         name='order-list'),
    path('order/create/',
         CreateView.as_view(
            model=Order,
            fields='__all__',
            success_url=reverse_lazy('orders:expense-list'),
            template_name='generic_update.html'
         ),
         name='order-create'),
    path('order/<int:pk>/edit/',
         UpdateView.as_view(
            model=Order,
            fields='__all__',
            success_url=reverse_lazy('orders:order-list'),
            template_name='generic_update.html'
         ),
         name='order-edit'),
    path('order/<int:pk>/delete/',
         DeleteView.as_view(
            model=Order,
            success_url=reverse_lazy('orders:order-list'),
            template_name='generic_delete.html'
         ),
         name='order-delete'),

    path('category/list/',
         CategoryListView.as_view(),
         name='category-list'),
    path('category/create/',
         CreateView.as_view(
            model=Category,
            fields='__all__',
            success_url=reverse_lazy('orders:category-list'),
            template_name='generic_update.html'
         ),
         name='category-create'),
    path('category/<int:pk>/edit/',
         UpdateView.as_view(
             model=Category,
             fields='__all__',
             success_url=reverse_lazy('orders:category-list'),
             template_name='generic_update.html'
         ),
         name='category-edit'),
    path('category/<int:pk>/delete/',
         DeleteView.as_view(
            model=Category,
            success_url=reverse_lazy('orders:category-list'),
            template_name='generic_delete.html'
         ),
         name='category-delete'),
]

project/urls.py
from django.urls import include, path
from django.views.generic.base import RedirectView

urlpatterns = [
    path('',
         RedirectView.as_view(pattern_name='orders:order-list'),
         name='dashboard'),
    path('orders/',
         include(('orders.urls', 'orders'), namespace='orders')),
]

orders/models.py
import datetime
from django.db import models


class Category(models.Model):
    class Meta:
        ordering = ('name',)

    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return f'{self.name}'


class Order(models.Model):
    class Meta:
        ordering = ('-date', '-pk')

    category = models.ForeignKey(Category, models.PROTECT, null=True, blank=True)
    name = models.CharField(max_length=50)
    amount = models.DecimalField(max_digits=8, decimal_places=2)
    date = models.DateField(default=datetime.date.today, db_index=True)
    
    def __str__(self):
        return f'{self.date} {self.name} {self.amount}'

orders/forms.py
from django import forms
from django.db.models import Count

from .models import Order, Category


class OrderSearchForm(forms.ModelForm):
    name = forms.CharField()
    start_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    end_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    categories = forms.ModelMultipleChoiceField(queryset=Category
                                                .objects
                                                .annotate(cnt=Count('order'))
                                                .filter(cnt__gt=0), widget=forms.CheckboxSelectMultiple)
    sort_by = forms.ChoiceField(choices=(
                ("date_desc", "date desc."),
                ("date", "date"),
                ("category", "category A-Z"),
                ("category_desc", "category Z-A"),
        ))

    class Meta:
        model = Order
        fields = ('name', 'start_date', 'end_date', 'categories', 'sort_by')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].required = False
        self.fields['start_date'].required = False
        self.fields['end_date'].required = False
        self.fields['categories'].required = False
        self.fields['sort_by'].required = False

orders/views.py
from django.views.generic.list import ListView
from datetime import date
from .forms import OrderSearchForm
from .models import Order, Category
from .reports import summary_per_category, get_min_date, summary_total, get_per_year_month_summary, get_about_categories


class OrderListView(ListView):
    model = Order
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        queryset = object_list if object_list is not None else self.object_list

        form = OrderSearchForm(self.request.GET)
        if form.is_valid():
            name = form.cleaned_data.get('name', '').strip()
            min_date = form.cleaned_data.get('start_date')
            max_date = form.cleaned_data.get('end_date')
            categories = form.cleaned_data.get('categories')
            sort_by = form.cleaned_data.get('sort_by')

            if name:
                queryset = queryset.filter(name__icontains=name)

            if min_date or max_date:
                if not min_date:
                    min_date = get_min_date(queryset)
                if not max_date:
                    max_date = date.today()
                queryset = queryset.filter(date__range=(min_date, max_date))

            if categories:
                category_list = []
                for c in categories:
                    category_list.append(c)
                queryset = queryset.filter(category__name__in=category_list)

            if sort_by:
                if sort_by == 'date_desc':
                    queryset = queryset.order_by('-date', '-pk')
                elif sort_by == 'date':
                    queryset = queryset.order_by('date', 'pk')
                elif sort_by == 'category':
                    queryset = queryset.order_by('category', 'name')
                elif sort_by == 'category_desc':
                    queryset = queryset.order_by('-category', '-name')

        return super().get_context_data(
            form=form,
            object_list=queryset,
            summary_per_category=summary_per_category(queryset),
            summary_total=summary_total(queryset),
            get_per_year_month_summary=get_per_year_month_summary(queryset),
            **kwargs)


class CategoryListView(ListView):
    model = Category
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        queryset = object_list if object_list is not None else self.object_list
        context = super().get_context_data(
            object_list=queryset,
            about_categories=get_about_categories(queryset),
            ** kwargs)
        return context

orders/templates/orders/category_list.html
{% extends "base.html" %}

{% block content %}
<a href="{% url 'orders:category-create' %}">add</a>

<table border="1">
	<thead>
		<tr>
			<th>name</th>
			<th>number of items</th>
			<th>actions</th>
		</tr>
	</thead>
	<tbody>
		{% for category in about_categories %}
		<tr>
			<td>
				{{ category }}
			</td>
			<td>
				{{ category.orders_cnt }}
			</td>
			<td>
				<a href="{% url 'orders:category-edit' category.id %}">edit</a>
				<a href="{% url 'orders:category-delete' category.id %}">delete</a>
			</td>
		</tr>
		{% endfor %}
	</tbody>
</table>
{% endblock %}

orders/templates/orders/order_list.html
{% extends "base.html" %}

{% block content %}

<a href="{% url 'orders:order-create' %}">add</a>

<form method="get" action="">
  {{form.as_p}}
  <button type="submit">search</button>
</form>
<br>
<table border="1">
	<caption>Orders</caption>
	<thead>
	  <tr>
		<th>no.</th>
		<th>category</th>
		<th>name</th>
		<th>amount</th>
		<th>date</th>
		<th>actions</th>
	  </tr>
	</thead>
	<tbody>

	{% for obj in object_list %}
	  <tr>
		<td>{{ page_obj.start_index|add:forloop.counter0 }}.</td>
		<td>{{ obj.category|default:"-" }}</td>
		<td>{{ obj.name|default:"-" }}</td>
		<td>{{ obj.amount|floatformat:2 }}</td>
		<td>{{obj.date}}</td>
		<td>
		  <a href="{% url 'orders:order-edit' obj.id %}">edit</a>
		  <a href="{% url 'orders:order-delete' obj.id %}">delete</a>
		</td>
	  </tr>
	  {% empty %}
	  <tr>
		<td colspan="5">no items</td>
	  </tr>
	{% endfor %}
	</tbody>
</table>

{% include "_pagination.html" %}
<hr>
<table border="1">
  <caption>Summary per category</caption>
  <tr>
    {% for category, total in summary_per_category.items %}
	<tr>
		<td>{{category}}:</td>
		<td>{{total|floatformat:2}}</td>
	</tr>
	{% endfor %}
  </tr>
</table>
<hr>
<table border="3">
    <tr>
        <td>Total:</td>
        <td>{{ summary_total|floatformat:2 }}</td>

    </tr>
</table>
<hr>
<table border="1">
    <caption>Total summary per year-month</caption>
    <thead>
    <tr>
        <th>period</th>
        <th>total</th>
    </tr>
    </thead>
    <tbody>

    {% for period, total in get_per_year_month_summary.items %}
    <tr>
        {% if period|length == 4 %}
        <td><b>{{ period }}</b></td>
        <td><b>{{ total|floatformat:2 }}</b></td>
        {% else %}
        <td>{{ period }}</td>
        <td>{{ total|floatformat:2 }}</td>
        {% endif %}
    </tr>
    {% empty %}
    <tr>
        <td colspan="5">no items</td>
    </tr>
    {% endfor %}

    </tbody>
 </table>
{% endblock %}

project/templates/_pagination.html
<div class="pagination">
    <span class="pagination__nav">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

project/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>{% block meta_title %}Orders app{% endblock %}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  </head>
  <body>
	<a href="{% url 'orders:order-list' %}">Orders</a> |
	<a href="{% url 'orders:category-list' %}">Categories</a> |
	<hr>
    {% block content %}{% endblock %}
  </body>
</html>

project/templates/generic_delete.html
{% extends "base.html" %}

{% block content %}

<h1>Confirm removing "{{object}}"</h1>
<form method="post" action="">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit">delete</button>
</form>

{% endblock %}

project/templates/generic_update.html
{% extends "base.html" %}

{% block content %}

<form method="post" action="">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit">save</button>
</form>

{% endblock %}